/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.EventQueue;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.bean.Cliente;
import model.bean.Smartphone;
import model.dao.ClienteDAO;
import model.dao.SmartphoneDAO;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author VictorLeuthier
 */
public class TelaSmartphone extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TelaCadastro
     */
    public TelaSmartphone() {
      	initComponents();
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSmartphone = new javax.swing.JLabel();
        txtCodigoCelular = new javax.swing.JTextField();
        txtNumeroSerie = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCorCadastro = new javax.swing.JTextField();
        txtCpfCadastro = new javax.swing.JTextField();
        
        lblCodigoCelular = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblCpfCliente = new javax.swing.JLabel();
        
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smartphones");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloSmartphone.setText("Smartphones");

       /* txtNumeroSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });*/

        lblCodigoCelular.setText("Codigo Celular");

        lblNumeroSerie.setText("Numero de serie");

        lblModelo.setText("Modelo");

        lblMarca.setText("Marca");
        
        lblCor.setText("Cor");
        
        lblCpfCliente.setText("Cpf cliente");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        JLabel lblCorCadastro = new JLabel("Cor");
        
        JLabel lblCpfCadastro = new JLabel("CPF Cliente");
        
//        txtCorCadastro = new JTextField();
//        txtCorCadastro.setColumns(10);
//        
//        txtCpfCadastro = new JTextField();
//        txtCpfCadastro.setColumns(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblCodigoCelular)
        						.addComponent(txtCodigoCelular, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
        					.addGap(28)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNumeroSerie)
        						.addComponent(txtNumeroSerie, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(btnSalvar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(20)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(btnExcluir, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(txtModelo, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        							.addGap(33)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(lblMarca)
        									.addGap(121))
        								.addComponent(txtCorCadastro))))
        					.addGap(39))
        				.addComponent(lblModelo))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCorCadastro)
        				.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnAtualizar, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCpfCadastro)
        				.addComponent(txtCpfCadastro, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE))
        			.addGap(1191))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(38)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblCodigoCelular)
        				.addComponent(lblNumeroSerie)
        				.addComponent(lblModelo)
        				.addComponent(lblMarca)
        				.addComponent(lblCorCadastro)
        				.addComponent(lblCpfCadastro))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtCodigoCelular, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtNumeroSerie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtModelo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtCorCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtCpfCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnSalvar)
        				.addComponent(btnExcluir)
        				.addComponent(btnAtualizar))
        			.addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Codigo celular", "Numero de serie", "Modelo", "Marca", "Cor", "CPF Cliente"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	if(jTable1.getSelectedRow() != -1){
    		Smartphone smartphone = new Smartphone();
        	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
        	
        	String codigoCelular = txtCodigoCelular.getText();
        	String numSerie = (txtNumeroSerie.getText());
        	String modelo = (txtMarca.getText());
    		String marca = (txtModelo.getText());
    		String cor = (txtCorCadastro.getText());
    		String cpf = (txtCpfCadastro.getText());
        	
        	//if (tamanhoOk(marca, nomeCliente, email)){
    			
    			
    			smartphone.setCodCelular(codigoCelular);
    			smartphone.setNumSerie(numSerie);
    			smartphone.setModelo(modelo);
    			smartphone.setMarca(marca);
    			smartphone.setCor(cor);
    			smartphone.setCpf(cpf);
    			
    			smartphoneDao.atualizar(smartphone);
    		
    			txtCodigoCelular.setText(null);
        		txtNumeroSerie.setText(null);
        		txtMarca.setText(null);
        		txtModelo.setText(null);			
    			txtCorCadastro.setText(null);
    			txtCpfCadastro.setText(null);
    			
//    		}else{
//    			JOptionPane.showMessageDialog(null,"- CPF deve conter 11 digitos\n- Telefone deve conter 11 digitos\n- Nome deve conter entre 3 e 101 caracteres"
//    					+ "\n- Email deve conter ate 51 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
//    			return;
//    		}
        	readJTable();
    	}
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                        	
    	if(jTable1.getSelectedRow() != -1){
    		txtCodigoCelular.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
    		txtNumeroSerie.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    		txtMarca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
    		txtModelo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
    		txtCorCadastro.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
    		txtCpfCadastro.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());

    	}
    }       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	Smartphone smartphone = new Smartphone();
    	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
    	
    	
    	String codigoCelular = (txtCodigoCelular.getText());
    	String numSerie = (txtNumeroSerie.getText());
    	String modelo = (txtMarca.getText());
		String marca = (txtModelo.getText());
		String cor = (txtCorCadastro.getText());
		String cpf = (txtCpfCadastro.getText());
    	
    	//if (tamanhoOk(codigoCelular, numSerie, modelo, marca, cor, cpf)){
    		
    		if (  (codigoCelular.matches("^[0-9]*$")) && (numSerie.matches("^[0-9]*$"))  ){
			
				smartphone.setCodCelular(codigoCelular);
				smartphone.setNumSerie(numSerie);
			}else{
				JOptionPane.showMessageDialog(null,"Codigo do celular ou numero de serie invalidos","Erro",JOptionPane.ERROR_MESSAGE);
				return;
			}
    	
			smartphone.setModelo(modelo);
			smartphone.setMarca(marca);
			smartphone.setCor(cor);
			
			//if (existeCpf(cpf)){
				
				if (buscarClientePorCpf(cpf) != null){
					smartphone.setCpf(cpf);
				}else{
					JOptionPane.showMessageDialog(null,"CPF nao encontrado","Erro",JOptionPane.ERROR_MESSAGE);
					return;
				}
				
//			}else{
//				JOptionPane.showMessageDialog(null,"CPF invalido ou inexistente","Erro",JOptionPane.ERROR_MESSAGE);
//				return;
//			}
						
			smartphoneDao.criar(smartphone);
		
			txtCodigoCelular.setText(null);
    		txtNumeroSerie.setText(null);
    		txtMarca.setText(null);
    		txtModelo.setText(null);			
			txtCorCadastro.setText(null);
			txtCpfCadastro.setText(null);
			
//		}else{
//			JOptionPane.showMessageDialog(null,"- O codigo celular deve conter 5 digitos\n- Numero de serie deve conter 11 digitos\n- A marca deve ter pelo menos 3 digitos\n- CPF deve conter 11 caracteres"
//					+ "\n- Modelo deve conter ate 30 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
//			return;
//		}
    	readJTable();
    	
    	
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	if(jTable1.getSelectedRow() != -1){
    		Smartphone smartphone = new Smartphone();
    		SmartphoneDAO smartphoneDao = new SmartphoneDAO();
    		
    		smartphone.setCodCelular(txtCodigoCelular.getText());
    		smartphoneDao.excluir(smartphone);    		
    		
    		txtCodigoCelular.setText(null);
    		txtNumeroSerie.setText(null);
    		txtMarca.setText(null);
    		txtModelo.setText(null);			
			txtCorCadastro.setText(null);
			txtCpfCadastro.setText(null);
			
			readJTable();

    	}else{
    		JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
    	}
    }                                        

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSmartphone().setVisible(true);
            }
        });
    }
    	   
    
	   
//	   private boolean tamanhoOk(String codCelular, String numSerie, String modelo, String marca, String cor, String cpfCliente){		   
//			  
//		   if (       ( (codCelular.length()) == 5)
//				   && ( (numSerie.length()) == 11) 
//				   && ( (modelo.length())  < 30 )
//				   && ( (marca.length())   >= 3 )
//				   && ( (cor.length())     < 30 ) 
//				   && ( (cpfCliente.length()) == 11 ) ){
//			   			return true;	
//			}else{
//				 return false;
//			}	
//	   }
	   
//	   private boolean existeCpf(String cpfCliente){
//		  if( TelaCliente.isValidCpf(cpfCliente)){
//			  return true;
//		  }
//		  return false;
//	   }
//	   
	   private Cliente buscarClientePorCpf(String cpf){
		   //if (existeCpf(cpf)){
			   
			   ClienteDAO clienteDao = new ClienteDAO();
			   return clienteDao.pesquisarPorCpf(cpf);
		       			
		   //}return null;
	   }
	   
	   
	   public void readJTable(){
	    	DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
	    	modelo.setRowCount(0);
	    	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
	    	
	    	for(Smartphone s: smartphoneDao.listar()){
	    		modelo.addRow(new Object[]{
	       				s.getCodCelular(),
	    				s.getNumSerie(),
	    				s.getMarca(),
	    				s.getModelo(),
	    				s.getCor(),
	    				s.getCpf()
	    				
	    		});
	    		
	    	}
	    }
    
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel lblTituloSmartphone;
    private javax.swing.JLabel lblCodigoCelular;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigoCelular;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtCorCadastro;
    private javax.swing.JTextField txtCpfCadastro;
    // End of variables declaration                   
    
    public void abrirTelaSmartphone() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaSmartphone frame = new TelaSmartphone();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
