/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.EventQueue;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author Bernardojr
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TelaCadastro
     */
    public TelaCliente() {
      	initComponents();
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        //quando clicar no fechar - close
        addWindowListener(new WindowAdapter(){
			public void windowClosing(WindowEvent e) {
				TelaCliente.this.dispose();
			}
		});
        
        setTitle("Clientes");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Clientes");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF");

        jLabel3.setText("Nome");

        jLabel4.setText("Telefone");

        jLabel5.setText("Email");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 182, Short.MAX_VALUE))
                            .addComponent(txtEmail)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       		Cliente cliente = new Cliente();
        	ClienteDAO clienteDao = new ClienteDAO();
        	
        	String strCpf = txtCpf.getText();
    		String telefone = txtTelefone.getText();
    		String nomeCliente = (txtNome.getText());
    		String email = (txtEmail.getText());
        	
        	if (tamanhoOk(telefone, nomeCliente, email)){
    			
    			if(strCpf.matches("^[0-9]*$")){
    				if (((isValidCpf(strCpf)) != true)){
    					JOptionPane.showMessageDialog(null,"CPF Invalido","Erro",JOptionPane.ERROR_MESSAGE);
    					return;
    				}else{
    					cliente.setCpf(strCpf);
    					}
    			}else{
    				JOptionPane.showMessageDialog(null,"CPF Invalido - Deve conter apenas números","Erro",JOptionPane.ERROR_MESSAGE);
    				return;
    			}
    			
    			if ((isValidEmailAddress(email)) != true ){
    				JOptionPane.showMessageDialog(null,"Email Invalido","Erro",JOptionPane.ERROR_MESSAGE);
    				return;
    			}else{
    				cliente.setEmail(email);
    			}
    		
    			if ((Character.isLetter(nomeCliente.charAt(0))) != true ){
    				JOptionPane.showMessageDialog(null,"Nome Invalido","Erro",JOptionPane.ERROR_MESSAGE);
    				return;
    			}
    			
    			cliente.setTelefone(telefone);
    			cliente.setNomeCli(nomeCliente);
    			clienteDao.atualizar(cliente);
    		
    			txtCpf.setText(null);
    			txtTelefone.setText(null);
    			txtNome.setText(null);
    			txtEmail.setText(null);
    			
    		}else{
    			JOptionPane.showMessageDialog(null,"- CPF deve conter 11 digitos\n- Telefone deve conter 11 digitos\n- Nome deve conter entre 3 e 101 caracteres"
    					+ "\n- Email deve conter ate 51 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
    			return;
    		}
        	readJTable();
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                        	
    	if(jTable1.getSelectedRow() != -1){
    		txtCpf.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
    		txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    		txtTelefone.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
    		txtEmail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());

    	}
    }       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	Cliente cliente = new Cliente();
    	ClienteDAO clienteDao = new ClienteDAO();
    	
    	String strCpf = txtCpf.getText();
		String telefone = txtTelefone.getText();
		String nomeCliente = (txtNome.getText());
		String email = (txtEmail.getText());
    	
    	if (tamanhoOk(telefone, nomeCliente, email)){
			
			if(strCpf.matches("^[0-9]*$")){
				if (((isValidCpf(strCpf)) != true)){
					JOptionPane.showMessageDialog(null,"CPF Invalido","Erro",JOptionPane.ERROR_MESSAGE);
					return;
				}else{
					cliente.setCpf(strCpf);
					}
			}else{
				JOptionPane.showMessageDialog(null,"CPF Invalido - Deve conter apenas números","Erro",JOptionPane.ERROR_MESSAGE);
				return;
			}
			
			if ((isValidEmailAddress(email)) != true ){
				JOptionPane.showMessageDialog(null,"Email Invalido","Erro",JOptionPane.ERROR_MESSAGE);
				return;
			}
		
			if ((Character.isLetter(nomeCliente.charAt(0))) != true ){
				JOptionPane.showMessageDialog(null,"Nome Invalido","Erro",JOptionPane.ERROR_MESSAGE);
				return;
			}
			
			if(!(telefone.matches("^[0-9]*$"))){
				JOptionPane.showMessageDialog(null,"Telefone invalido","Erro",JOptionPane.ERROR_MESSAGE);
				return;					
			}	
			
			cliente.setTelefone(telefone);
			cliente.setNomeCli(nomeCliente);
			cliente.setEmail(email);
			clienteDao.criar(cliente);
		
			txtCpf.setText(null);
			txtTelefone.setText(null);
			txtNome.setText(null);
			txtEmail.setText(null);
			
		}else{
			JOptionPane.showMessageDialog(null,"- CPF deve conter 11 digitos\n- Telefone deve conter 11 digitos\n- Nome deve conter entre 3 e 101 caracteres"
					+ "\n- Email deve conter ate 51 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
			return;
		}
    	readJTable();
    	
    	
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	if(jTable1.getSelectedRow() != -1){
    		Cliente cliente = new Cliente();
    		ClienteDAO clienteDao = new ClienteDAO();
    		
    		cliente.setCpf(txtCpf.getText());
    		clienteDao.excluir(cliente);
    		
    		txtCpf.setText(null);
			txtTelefone.setText(null);
			txtNome.setText(null);
			txtEmail.setText(null);
			
			readJTable();

    	}else{
    		JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
    	}
    }                                        

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }
    
    private boolean isValidEmailAddress(String email){
        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
        java.util.regex.Matcher m = p.matcher(email);
        return m.matches();
	   }
	   
	   
	   private boolean tamanhoOk(String telefone, String nomeCliente, String email){		   
			  
		   if (    (telefone.length()) == 11  || (telefone.length()) == 8 
				   && ( (nomeCliente.length()) < 101 && (nomeCliente.length()) > 3 )
				   && ( (email.length()) < 51) ){
			   			return true;	
			}else{
				 return false;
			}	
	   }
	   
	   

	   private static final int[] pesoCPF = {11, 10, 9, 8, 7, 6, 5, 4, 3, 2};
	   private static int calcularDigito(String str, int[] peso) {
	      int soma = 0;
	      
	      for (int indice=str.length()-1, digito; indice >= 0; indice-- ) {
	         digito = Integer.parseInt(str.substring(indice,indice+1));
	         soma += digito*peso[peso.length-str.length()+indice];
	      }
	      
	      soma = 11 - soma % 11;
	      return soma > 9 ? 0 : soma;
	      
	   }

	   
	   public static boolean isValidCpf(String cpf) {
		   
	      if ( (cpf==null) || (cpf.length()!=11) ||
	    		  cpf.equals("00000000000") || cpf.equals("11111111111") ||
	    		  cpf.equals("22222222222") || cpf.equals("33333333333") ||
	    	      cpf.equals("44444444444") || cpf.equals("55555555555") ||
	    	      cpf.equals("66666666666") || cpf.equals("77777777777") ||
	    	      cpf.equals("88888888888") || cpf.equals("99999999999") ) {
	    	  return false;
	      }

	      Integer digito1 = calcularDigito(cpf.substring(0,9), pesoCPF);
	      Integer digito2 = calcularDigito(cpf.substring(0,9) + digito1, pesoCPF);
	      return cpf.equals(cpf.substring(0,9) + digito1.toString() + digito2.toString());
	  
	   }
	   
	   public void readJTable(){
	    	DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
	    	modelo.setRowCount(0);
	    	ClienteDAO clientedao = new ClienteDAO();
	    	
	    	for(Cliente c: clientedao.listar()){
	    		modelo.addRow(new Object[]{
	       				c.getCpf(),
	    				c.getNomeCli(),
	    				c.getTelefone(),
	    				c.getEmail()
	    		});
	    		
	    	}
	    }
    
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration                   
    
    public void abrirTelaCliente() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaCliente frame = new TelaCliente();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
