/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.EventQueue;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.bean.Smartphone;
import model.dao.SmartphoneDAO;

/**
 *
 * @author VictorLeuthier
 */
public class TelaSmartphone extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TelaCadastro
     */
    public TelaSmartphone() {
      	initComponents();
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoCelular = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNumeroSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smartphones");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Smartphones");

        txtNumeroSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Celular");

        jLabel3.setText("Numero de serie");

        jLabel4.setText("Modelo");

        jLabel5.setText("Marca");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(63, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(63, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 182, Short.MAX_VALUE))
                            .addComponent(txtNumeroSerie)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Numero de serie", "Modelo", "Marca", "Cor", "CPF Cliente"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) 
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	if(jTable1.getSelectedRow() != -1){
    		Smartphone smartphone = new Smartphone();
        	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
        	
        	String codigoCelular = txtCodigoCelular.getText();
        	String numSerie = (txtNumeroSerie.getText());
        	String modelo = (txtModelo.getText());
    		String marca = (txtMarca.getText());
    		String cor = (txtCor.getText());
    		String cpf = (txtCpf.getText());
        	
        	//if (tamanhoOk(marca, nomeCliente, email)){
    			
    			
    			smartphone.setCodCelular(codigoCelular);
    			smartphone.setNumSerie(numSerie);
    			smartphone.setModelo(modelo);
    			smartphone.setMarca(marca);
    			smartphone.setCor(cor);
    			smartphone.setCpf(cpf);
    			
    			smartphoneDao.criar(smartphone);
    		
    			txtCodigoCelular.setText(null);
        		txtNumeroSerie.setText(null);
        		txtModelo.setText(null);
        		txtMarca.setText(null);			
    			txtCor.setText(null);
    			txtCpf.setText(null);
    			
//    		}else{
//    			JOptionPane.showMessageDialog(null,"- CPF deve conter 11 digitos\n- Telefone deve conter 11 digitos\n- Nome deve conter entre 3 e 101 caracteres"
//    					+ "\n- Email deve conter ate 51 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
//    			return;
//    		}
        	readJTable();
    	}
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                        	
    	if(jTable1.getSelectedRow() != -1){
    		txtCodigoCelular.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
    		txtModelo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    		txtMarca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
    		txtNumeroSerie.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());

    	}
    }       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	Smartphone smartphone = new Smartphone();
    	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
    	
    	
    	String codigoCelular = (txtCodigoCelular.getText());
    	String numSerie = (txtNumeroSerie.getText());
    	String modelo = (txtModelo.getText());
		String marca = (txtMarca.getText());
		String cor = (txtCor.getText());
		String cpf = (txtCpf.getText());
    	
    	//if (tamanhoOk(marca, nomeCliente, email)){
			
			
			smartphone.setCodCelular(codigoCelular);
			smartphone.setNumSerie(numSerie);
			smartphone.setModelo(modelo);
			smartphone.setMarca(marca);
			smartphone.setCor(cor);
			smartphone.setCpf(cpf);
			
			smartphoneDao.criar(smartphone);
		
			txtCodigoCelular.setText(null);
    		txtNumeroSerie.setText(null);
    		txtModelo.setText(null);
    		txtMarca.setText(null);			
			txtCor.setText(null);
			txtCpf.setText(null);
			
//		}else{
//			JOptionPane.showMessageDialog(null,"- Numero de serie deve conter 11 digitos\n- A marca deve ter +3 dígitos\n- CPF deve "
//					+ "\n- Modelo deve conter ate 30 caracteres","Erro",JOptionPane.ERROR_MESSAGE);
//			return;
//		}
    	readJTable();
    	
    	
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	if(jTable1.getSelectedRow() != -1){
    		Smartphone smartphone = new Smartphone();
    		SmartphoneDAO smartphoneDao = new SmartphoneDAO();
    		
    		smartphone.setCodCelular(txtCodigoCelular.getText());
    		smartphoneDao.excluir(smartphone);    		
    		
    		txtCodigoCelular.setText(null);
    		txtNumeroSerie.setText(null);
    		txtModelo.setText(null);
    		txtMarca.setText(null);			
			txtCor.setText(null);
			txtCpf.setText(null);
			
			readJTable();

    	}else{
    		JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
    	}
    }                                        

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSmartphone().setVisible(true);
            }
        });
    }
    	   
	   
	   private boolean tamanhoOk(String numSerie, String modelo, String marca, String cor, String cpfCliente){		   
			  
		   if (    (numSerie.length()) == 11 
				   && ( (modelo.length())  < 30 )
				   && ( (marca.length())   >= 3 )
				   && ( (cor.length())     < 30 ) 
				   && ( (cpfCliente.length() == 11 ))  ) {
			   			return true;	
			}else{
				 return false;
			}	
	   }
	   
	   
	   public void readJTable(){
	    	DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
	    	modelo.setRowCount(0);
	    	SmartphoneDAO smartphoneDao = new SmartphoneDAO();
	    	
	    	for(Smartphone s: smartphoneDao.listar()){
	    		modelo.addRow(new Object[]{
	       				s.getCodCelular(),
	    				s.getNumSerie(),
	    				s.getMarca(),
	    				s.getModelo(),
	    				s.getCor(),
	    				s.getCpf()
	    				
	    		});
	    		
	    	}
	    }
    
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigoCelular;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration                   
    
    public void abrirTelaSmartphone() {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TelaSmartphone frame = new TelaSmartphone();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
